### ISSUE TITLE
FormWizard does not support internationalization of named wizard steps

### ISSUE THREAD

**Issue by lulumuts** [jazzband/django-formtools#135]
Hi all, I'm trying to translate my django app, and all aspects work except for the formtools wizard, specifically the strings assigned to my multistep forms. In Urls.py I have:

named_formwizard_forms = (
    (_('Your Details'), FormStepOne),
    (_('Residence Preference'), FormStepTwo),
    (_('Immigration & Schooling'), FormStepThree),
    (_('Mobility Expenses'), FormStepFour),
    (_('Living Expenses'), FormStepFive),
)
urlpatterns = [
path(_('form/'), FormWizardView.as_view(named_formwizard_forms),name="form"),
]
When I makemessages, the strings show up in my django.po, and while i have translated them to french, they either do not compile or there is some format I am missing in the template.
Please advise.

Thanks

**Comment by claudep** [comment]
Shouldn't your strings be `_('Your Details')` instead of `('Your Details')`?

**Comment by lulumuts** [comment]
Hi my mistake, this is the way the code actually looks, can't say why it copied without the underscore. 

named_formwizard_forms = (
    (_('Your Details'), FormStepOne),
    (_('Residence Preference'), FormStepTwo),
    (_('Immigration & Schooling'), FormStepThree),
    (_('Mobility Expenses'), FormStepFour),
    (_('Living Expenses'), FormStepFive),
   
)
urlpatterns = [
path(('form/'), FormWizardView.as_view(named_formwizard_forms),name="form"),
]

Any idea why it shows up in my .po file but doesnt translate? I suspect formtools only translates from the django formtools LOCALE folder?

**Comment by claudep** [comment]
Your are aliasing `_` to `gettext_lazy` not `gettext`, right?

**Comment by lulumuts** [comment]
yes exactly

**Comment by claudep** [comment]
In fact, I dont think the form step name is supposed to be translated, as it is forced to a string soon in its processing. It is just a step name that should be used in the code, not a string to be presented to the user. You can probably store user-visible strings inside the form themselves.
