### ISSUE TITLE
Django 3.0 compatibility

### ISSUE THREAD

**Issue by rixx** [jazzband/django-formtools#142]
Django will remove the vendored `django.utils.six` in the upcoming 3.0 release. `six` is in use in django-formtools for normalization of string types and iteration.

Since I see that the next version of django-formtools will drop support for Django versions 1.10 and below, and will add support for 2.1, the smoothest experience for everybody concerned would probably be to depend on `six` directly for a bit?

**Comment by juancferrer** [comment]
Any updates on this?  I'm trying to upgrade my project to use Django 3.0 and it seems that formtools/utils.py is importing django.utils.six which is now deprecated.

**Comment by juancferrer** [comment]
I see the source installed from pypi is still using six, but the latest code on github doesn't.
I guess there hasn't been a new pypi release with these latest changes?

**Comment by juancferrer** [comment]
I just added this to my requirements.txt and my project is back to normal, using django 3.0

-e git+git://github.com/jazzband/django-formtools@db1f4f4049d913a3774a0edcf5107203b8a15e91#egg=formtools


Maybe there can be a new PyPi release, so we don't have to have this in requirements.txt ?

**Comment by loop0** [comment]
It would be awesome to have a new release in order to use it in django 3

**Comment by hramezani** [comment]
Soon we can have new PyPi releases compatible with `Django 3.0`. 
[The new version](https://github.com/jazzband/django-formtools/commit/6aace6b653d0d4ba6a0130695006172cee4d1b92) is created already.

**Comment by loop0** [comment]
What is keeping us from releasing it to pypi?

**Comment by claudep** [comment]
A releaser!

**Comment by timgraham** [comment]
django-formtools 2.2 (with Django 3.0 compatibility) is now on PyPI.
