### ISSUE TITLE
Django 2.2?

### ISSUE THREAD

**Issue by tripptuttle** [jazzband/django-formtools#143]
Are there known issues with Django 2.2.3 and Formtools 2.1? Specifically with the use of ModelChoiceFields? I've been having never-ending form wizard loops a 2.2.3 project. Nothing gets logged, but when I "submit" the final step in the wizard, it just takes me back to the first step, as if the "done" method in my SessionWizardView subclass is never called. Has anyone else encountered this type of error? I've tried removing all model-derived fields and I am still running into the issue.

I'm partially going crazy here, as I can't seem to find anyone else running into this issue. Thanks for helping point me in the right direction, and confirming that this isn't a version compatibility issue. 

If there are any known issues, perhaps updating the docs would be a good idea, as they lead one to believe that formtools should work fine with Django.
> New releases of django-formtools should always be compatible with the latest stable release of Django. If a new version of Django contains backwards incompatible changes that affect formtools, a new release of formtools will be issued shortly after the release of the new Django version. 

[code-example.txt](https://github.com/django/django-formtools/files/3369832/code-example.txt)

**Comment by ChristianLan1** [comment]
I installed with "pip3 install django-formtools", but it still says "ModuleNotFoundError: No module named 'django-formtools'."  Is this the issue for everyone using Django 2.2?

**Comment by violuke** [comment]
@ChristianLan1 This is the problem that I have

**Comment by timgraham** [comment]
django-formtools 2.2 (tested with Django 2.2) is now on PyPI. If you still have trouble, please investigate and explain why formtools is at fault.
