### ISSUE TITLE
Maybe time for a release?

### ISSUE THREAD

**Issue by fallen** [jazzband/django-formtools#150]
Django 3.0 will soon be out there, and the latest release of django-formtools cannot work on Django 3 because Python 2 support was dropped (no django.utils.six anymore.).
I can see that Python 2 (and therefore usage of six) is already dropped from master here.
But until there is a release, it's not possible to use this on Django 3.
Please do some release and publish it on pypi so that django-formtools can be used with Django 3.

**Comment by martey** [comment]
> But until there is a release, it's not possible to use this on Django 3.

I've seen this canard ("if there isn't a release on PyPi, I can't install the changes/updates made recently") a lot, and it's not true. You can use [an editable installation](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) to install directly from the Git repository:

`pip install -e git+https://github.com/jazzband/django-formtools#egg=django-formtools`

**Comment by fallen** [comment]
That is true. But it's also true that a lot of people are reluctant from using in production something that is not a release.

**Comment by claudep** [comment]
@timgraham Do you think you would be able to help for a release, you seem to be authorized on Pypi?

**Comment by timgraham** [comment]
Sure. Anything to be done besides pushing a tag and uploading to PyPI?

**Comment by claudep** [comment]
Awesome!
Maybe update the (too optimistic) release date in `docs/changelog.rst`. The rest should be ready™ in my point of view.

**Comment by timgraham** [comment]
django-formtools 2.2 is now on PyPI.

**Comment by claudep** [comment]
Our hero of the day \o/

**Comment by felixxm** [comment]
Thanks🏅

**Comment by fallen** [comment]
Thanks a lot @claudep and @timgraham ! :)
