### ISSUE TITLE
ManagementForm data is missing or has been tampered with

### ISSUE THREAD

**Issue by Mushahid2521** [jazzband/django-formtools#153]
I have been struggling with this for a long time. Will you please help me on this. This is not letting me sleep for a long time. Please help.
My view
`def daily_report_create_view(request):
    district = 'Natore'
    if request.method == 'GET':
        form = DAILY_REPORT_FORM(request.POST)
        g1_form = G1_FORM()
        g2_form = G2_FORM()
        g3_form = G3_FORM()
        g4_form = G4_FORM()
        g5_form = G5_FORM()
        g6_form = G6_FORM()
        g7_form = G7_FORM()
        g8_formset = G8_FormSet(request.POST)

    elif   request.method == 'POST':
        form = DAILY_REPORT_FORM(request.POST)
        # familyMemberFormeset = FamilyMemberFormSet(request.POST)
        g1_form = G1_FORM(request.POST)
        g2_form = G2_FORM(request.POST)
        g3_form = G3_FORM(request.POST)
        g4_form = G4_FORM(request.POST)
        g5_form = G5_FORM(request.POST)
        g6_form = G6_FORM(request.POST)
        g7_form = G7_FORM(request.POST)
        g8_formset = G8_FormSet(request.POST)

        if form.is_valid() and g1_form.is_valid() and g2_form.is_valid() and g3_form.is_valid() and g4_form.is_valid()\
                and g5_form.is_valid() and g6_form.is_valid() and g7_form.is_valid() and g8_formset.is_valid():

            print(g8_formset.cleaned_data)

    context = {
        'form': form,
        'g1_form': g1_form,
        'g2_form': g2_form,
        'g3_form': g3_form,
        'g4_form': g4_form,
        'g5_form': g5_form,
        'g6_form': g6_form,
        'g7_form': g7_form,
        'g8_formset': g8_formset
    }

    return render(request, 'morningReport/report_create.html', context)`

My template:
`    {{ g8_formset.management_form }}
    {% for link_form in g8_formset %}
        <div class="link-formset">

            {{ link_form.as_p }}

        </div>
    {% endfor %}`

**Comment by claudep** [comment]
Sorry, but nothing in your report indicate that django-formtools is used at all. I'd suggest using a django users forum for your question (https://forum.djangoproject.com/c/users by example).

**Comment by Mushahid2521** [comment]
I have been using inline formset factory 
`G8_FormSet = inlineformset_factory(DAILY_REPORT_MODEL, G8MODEL,
                                            form=G8_FORM, extra=1)`

**Comment by claudep** [comment]
`inlineformset_factory` is standard Django.
https://docs.djangoproject.com/en/2.2/ref/forms/models/#django.forms.models.inlineformset_factory

**Comment by Mushahid2521** [comment]
Brother I am getting the error of the title. [Here](https://github.com/jazzband/django-formtools/issues/131) this is the same issue asked but I couldn't make it right after using the solution of this issue as well. Still the error occurs. Please let me know if I need to paste all the codes to make it  more understandable.

**Comment by Mushahid2521** [comment]
@claudep help me bro

**Comment by claudep** [comment]
I wrote to your gmail address, this issue is not the location to handle your problem.
