### ISSUE TITLE
Is ajax supported?

### ISSUE THREAD

**Issue by lilboat72** [jazzband/django-formtools#171]
Was wondering if this library supports form submission by ajax. For example, i would like to send an ajax request to the server, perform some stuff then retrieve the form without refreshing the page.

**Comment by globophobe** [comment]
WizardView is a regular Django view which processes one form, and then another form, with validation steps, until all forms are done. Temporary data is typically stored in session store. 

There is no reason you could not use combine WizardView with ajax requests. However, if you're going to use ajax you may find it easier to just create some views, and use JavaScript to manage the form steps.

**Comment by lilboat72** [comment]
Mhhh i see. So as an alternative to my problem, is there a way to carry validations on your own. Like i want to modify the   **request FormData** that is passed by ajax before i call `form.is_valid(...)`. All methods as specified in the docs deal specifically with post(after) handling of data. I even posted the problem on Stackoverflow [https://stackoverflow.com/q/64017446/11345948](url).

**Comment by globophobe** [comment]
Subclass WizardView and override `post` https://github.com/jazzband/django-formtools/blob/965769d791a82fd32b3f70613c6785008eca3a4b/formtools/wizard/views.py#L291

**Comment by lilboat72** [comment]
OMG what a huge coincidence. I was literally doing that 10 min ago. Anyway thanks a lot 👍🏿
