### ISSUE TITLE
error save m2m django 3.0.8 and django-formtools==2.2

### ISSUE THREAD

**Issue by CARocha** [jazzband/django-formtools#173]
Hi, when i try save data into database
data = {k: v for form in form_list for k, v in form.cleaned_data.items()} 
instance = MyModels.objects.create(**data). #in data send my 2 fields m2m  :/ django say this error
Direct assignment to the forward side of a many-to-many set is prohibited. Use sintomas.set() instead.

any idea how to solve this please!!

Cheers

**Comment by claudep** [comment]
This has nothing to do with django-formtools, in Django you have to set object values for ManyToMany Field's in a separate `instance.<m2m_field>.set(values)` line.

**Comment by CARocha** [comment]
Hi, @claudep yes thank but you see in data include m2m fields, any idea separated field not m2m for working save and them save instance.m2m.set() :/ the problem is this line nstance = MyModels.objects.create(**data) data include all fields fk,m2m,fields 

Cheers

**Comment by claudep** [comment]
If you create objects by yourself, than it's your task to separate form data to be able to save m2m fields separately. You can see an example of that happening in Django's own ModelForm save() method (https://github.com/django/django/blob/master/django/forms/models.py#L445).
