### ISSUE TITLE
Replace Travis-CI by GitHub Actions

### ISSUE THREAD

**Issue by claudep** [jazzband/django-formtools#187]
Unfortunately, Travis-CI recently became unusable for open source projects. Anyone to create a GitHub Actions config for django-formtools?

**Comment by hramezani** [comment]
Hi @claudep, 
I can work on this.

**Comment by claudep** [comment]
Great, I know @jezdez also have a plan to some mass-conversion for Jazzband projects.

**Comment by jezdez** [comment]
No need to work on this @hramezani, thank you for the offer though. I'm converting all projects to GHA this week. More news forthcoming..

**Comment by jezdez** [comment]
This is now pending review in #188
