### ISSUE TITLE
Possibility of a new PyPI release?

### ISSUE THREAD

**Issue by umgelurgel** [jazzband/django-formtools#195]
Looks like there hasn't been a new release since 2019 - given that Django 3.2 LTS has been released recently, would it be possible to have a new version of the module released to PyPI? 

Related https://github.com/jazzband/django-formtools/issues/150

**Comment by rtpg** [comment]
Alright going to try and get the ball rolling for this with #196

**Comment by umgelurgel** [comment]
Thank you! :pray:
