### ISSUE TITLE
Invalid CSRF Fail

### ISSUE THREAD

**Issue by Alfareiza** [jazzband/django-formtools#229]
In the process of buidling my multistep form using django-formtools, I've faced with this situation, and I'd like some help or advice to figure out it.

At the moment when I'm doing a POST request call to this view, this message appear. This is is basically a form. You can see in the image that Django suggest add a decorator `{% csrf_protect %}` in all the views that has a `{% csrf_token %}` on their forms. But as I don't have views according to the implementation of django-formtools, I don't know how to proceed.

![2022-11-07 19 33 16 24b4-2804-14d-3281-86ee-547c-d27e-39f8-5f0c sa ngrok io 2261e75aa7db](https://user-images.githubusercontent.com/63620799/200685122-cec3b7d9-020e-4e4c-a133-4927674e02dc.png)

[This is the REPOSITORY](https://github.com/Alfareiza/logifarma-radicar-domicilio)

**Comment by claudep** [comment]
You should check for "django origin checking failed" in a search engine or find help in Django forums. Your issue is not specifically linked to django-formtools.
